version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: consumptionTracker-app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - ADDRESS_SERVICE_URL=${ADDRESS_SERVICE_URL}
      - API_TOKEN=${API_TOKEN}
    depends_on:
      - db
    networks:
      - biatest-network


  db:
    image: postgres:latest
    container_name: consumptionTracker_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/consumptions.csv:/docker-entrypoint-initdb.d/consumptions.csv
    networks:
      - biatest-network

volumes:
  postgres_data:

networks:
  bia-network:
    driver: bridge